myapp/app/urls.py
from django.conf.urls import patterns, url
from app import views
from task import views as t_view
#from  notice import  views as n_views

urlpatterns = patterns('',
                       # url(r'^$', views.index, name='index'),
                       # url(r'^test/$', t_view.created_task),
                       url(r'^login/$', views.user_login),
                       url(r'^logout/$', views.user_logout),
                       url(r'^change_password/$', views.change_password),
)

myapp/grappelli/urls.py
# coding: utf-8

# DJANGO IMPORTS
try: 
    from django.conf.urls import url, patterns
except ImportError: 
    # for Django version less then 1.4
    from django.conf.urls.defaults import url, patterns

from django.views.generic.base import TemplateView
from .views.related import RelatedLookup, M2MLookup, AutocompleteLookup
from .views.switch import switch_user


urlpatterns = patterns('',

    # FOREIGNKEY & GENERIC LOOKUP
    url(r'^lookup/related/$', RelatedLookup.as_view(), name="grp_related_lookup"),
    url(r'^lookup/m2m/$', M2MLookup.as_view(), name="grp_m2m_lookup"),
    url(r'^lookup/autocomplete/$', AutocompleteLookup.as_view(), name="grp_autocomplete_lookup"),

    # SWITCH USER
    url(r'^switch/user/(?P<object_id>\d+)/$', switch_user, name="grp_switch_user"),

    # GRAPPELLI DOM DOCUMENTATION
    url(r'^grp-doc/change-form/', TemplateView.as_view(template_name='grp_doc/change_form.html'), name="grp_doc_change_form"),
    url(r'^grp-doc/change-list/', TemplateView.as_view(template_name='grp_doc/change_list.html'), name="grp_doc_change_list"),
    url(r'^grp-doc/admin-index/', TemplateView.as_view(template_name='grp_doc/admin_index.html'), name="grp_doc_admin_index"),

    url(r'^grp-doc/tables/', TemplateView.as_view(template_name='grp_doc/tables.html'), name="grp_doc_tables"),

    url(r'^grp-doc/pagination/', TemplateView.as_view(template_name='grp_doc/pagination.html'), name="grp_doc_pagination"),
    url(r'^grp-doc/search-form/', TemplateView.as_view(template_name='grp_doc/search_form.html'), name="grp_doc_search_form"),
    url(r'^grp-doc/filter/', TemplateView.as_view(template_name='grp_doc/filter.html'), name="grp_doc_filter"),
    url(r'^grp-doc/date-hierarchy/', TemplateView.as_view(template_name='grp_doc/date_hierarchy.html'), name="grp_doc_date_hierarchy"),

    url(r'^grp-doc/fieldsets/', TemplateView.as_view(template_name='grp_doc/fieldsets.html'), name="grp_doc_fieldsets"),
    url(r'^grp-doc/errors/', TemplateView.as_view(template_name='grp_doc/errors.html'), name="grp_doc_errors"),
    url(r'^grp-doc/form-fields/', TemplateView.as_view(template_name='grp_doc/form_fields.html'), name="grp_doc_form_fields"),
    url(r'^grp-doc/submit-rows/', TemplateView.as_view(template_name='grp_doc/submit_rows.html'), name="grp_doc_submit_rows"),

    url(r'^grp-doc/modules/', TemplateView.as_view(template_name='grp_doc/modules.html'), name="grp_doc_modules"),
    url(r'^grp-doc/groups/', TemplateView.as_view(template_name='grp_doc/groups.html'), name="grp_doc_groups"),

    url(r'^grp-doc/navigation/', TemplateView.as_view(template_name='grp_doc/navigation.html'), name="grp_doc_navigation"),
    url(r'^grp-doc/context-navigation/', TemplateView.as_view(template_name='grp_doc/context_navigation.html'), name="grp_doc_context_navigation"),

    url(r'^grp-doc/basic-page-structure/', TemplateView.as_view(template_name='grp_doc/basic_page_structure.html'), name="grp_doc_basic_page_structure"),

    url(r'^grp-doc/tools/', TemplateView.as_view(template_name='grp_doc/tools.html'), name="grp_doc_tools"),
    url(r'^grp-doc/object-tools/', TemplateView.as_view(template_name='grp_doc/object_tools.html'), name="grp_doc_object_tools"),

    url(r'^grp-doc/mueller-grid-system-tests/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system_tests.html'), name="grp_doc_mueller_grid_system_tests"),
    url(r'^grp-doc/mueller-grid-system/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system.html'), name="grp_doc_mueller_grid_system"),
    url(r'^grp-doc/mueller-grid-system-layouts/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system_layouts.html'), name="grp_doc_mueller_grid_system_layouts"),

    url(r'^grp-doc', TemplateView.as_view(template_name='grp_doc/index.html'), name="grp_doc"),

)

myapp/myapp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from filebrowser.sites import site

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myapp.views.home', name='home'),
    # url(r'^myapp/', include('myapp.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:

    url(r'^$','app.views.index',name='Home'),
    url(r'^app/', include('app.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^calendar/', include('myCalendar.urls')),

    url(r'^staff/', include('staff.urls')),
    url(r'^notice/', include('notice.urls')),
    url(r'^meeting/', include('meeting.urls')),
    url(r'^task/', include('task.urls')),
    url(r'^bug/', include('bug.urls')),
    url(r'^filebrowser/', include(site.urls)),
)
urlpatterns += staticfiles_urlpatterns()

myapp/notice/urls.py
__author__ = 'whiteworld'
from  django.conf.urls import patterns, url
from  notice import views
from django.views.decorators.cache import cache_page
urlpatterns = patterns('',
                       url(r'^$',views.index),
                       url(r'^get_notice/$', views.get_notice),
                       url(r'^create_notice/$', views.create_notice),
                       url(r'^detail_notice/(?P<id>\d+)/$', views.detail_notice),
                       url(r'^delete_notice/(?P<id>\d+)/$', views.delete_notice),
)

myapp/notice/models.py
from django.db import models

# Create your models here.

myapp/notice/views.py
#-*- coding: UTF-8 -*-
# Create your views here.
from  app.models import Notice, Staff
from  django.template import RequestContext
from  django.shortcuts import  render_to_response,render,get_object_or_404,redirect
from  django.http import HttpResponse, HttpResponseRedirect
from  django.contrib.auth import authenticate,login,logout
from django import  forms
from  django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from  app.views import permission_required_with, cache_on_auth
from  datetime import  datetime
from django.core.cache import cache
from django.views.decorators.cache import cache_page
from django.db import router, transaction


class NoticeForm(forms.ModelForm):
    title = forms.CharField()
    time = forms.DateTimeField()
    content = forms.Textarea()

    class Meta:
        model = Notice
        exclude = ('creator',)
@login_required(login_url="/app/login/")
#@permission_required_with('notice')
def index(request):
    cache.clear()
    context = RequestContext(request)
    notices = Notice.objects.all()
    return  render_to_response('notice/index.html',{'staff': request.user.staff,'notices':notices},context)

@login_required(login_url="/app/login/")
#@permission_required_with('notice')
# @cache_on_auth(60*5)
def get_notice(request):
    context = RequestContext(request)
    notices = Notice.objects.all().order_by('-time')

    return  render_to_response('notice/notice_list.html',{'notice_list':notices,'url':request.path,'staff':request.user.staff},context)

@login_required(login_url="/app/login/")
#@permission_required_with('notice')
def detail_notice(request,id):
    context = RequestContext(request)
    notice = Notice.objects.get(id=id)
    enablecalendar = request.user.staff.role.editCalendar
    calendar = request.user.staff.visibleCalendar.all()
    return render_to_response('notice/detail_notice.html',{'calendar': calendar, 'enCalendar': enablecalendar,'staff': request.user.staff,'notice':notice},context)


@login_required(login_url='/app/login/')
def delete_notice(request, id):
    context = RequestContext(request)
    Notice.objects.get(id=id).delete()
    cache.clear()
    messages.success(request,"删除成功！")
    notices = Notice.objects.all().order_by('-time')
    return  render_to_response('notice/notice_list.html',{'notice_list':notices,'url':request.path,'staff':request.user.staff},context)


@login_required(login_url="/app/login/")
#@permission_required_with('notice')
def create_notice(request):
    context = RequestContext(request)
    if request.method == 'POST':
        nf = NoticeForm(request.POST)
        if nf.is_valid():
            nf_comment=nf.save(commit=False)
            nf_comment.creator = request.user.staff
            nf_comment.save()
            cache.clear()

            messages.success(request,"创建通知成功!")
            return redirect("/notice/get_notice/")
        else:
            title = request.POST.get('title')
            content = request.POST.get('content')
            time = request.POST.get('time')
            if title == '':
                messages.error(request,"请填写标题！")
            elif time == '':
                messages.error(request,'请选择时间！')
            elif content == '':
                messages.error(request,'请填写内容！')
            elif time != '':
                messages.error(request,'时间格式不正确！')
            elif len(title) > 30:
                messages.error(request,'标题太长（应不大于30个字）！')

            return render_to_response('notice/create_notice.html',
                                      {'staff': request.user.staff,'title':title,'content':content,'time':time},
                                      context)
    return render_to_response('notice/create_notice.html',{'staff': request.user.staff},context)

myapp/templates/notice/create_notice.html
{% extends 'app/layout.html' %}
{% block first %}
{% include "messages.html" %}
{% include "frame.html" %}
<legend><h1>发布通知</h1></legend>
<form method="post" class="form-horizontal" action="/notice/create_notice/">
    <div class="control-group">
        <label class="control-label" for="id_title">标题:<span style="color: red">&lowast;</span></label>
        <div class="controls">
            <input id="id_title" name="title" type="text" value="{{ title }}" />
        </div>
    </div>

    <div class="control-group">
        <label  class="control-label" for="id_time">时间:<span style="color: red">&lowast;</span></label>
        <div class="controls">
            <input id="id_time" name="time" type="text" value="{{ time }}">(格式: YYYY-MM-DD)
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="id_content">内容:<span style="color: red">&lowast;</span></label>
        <div class="controls">
            <textarea cols="40" id="id_content" name="content"  rows="10">{{ content }}</textarea>
        </div>
    </div>

    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn btn-primary toTop">发布</button>
            <button class="btn btn-primary back_button toTop" iid="create_notice">清空</button>
        </div>
    </div>
</form>
        <script>
     $(document).ready(function () {
        $('.nav li').removeClass('active');
        $('.create_notice_select').parent().addClass('active');

    });
    </script>
{% endblock %}

myapp/templates/notice/detail_notice.html
{% load dictionary_extras %}
<br/>
<br/>
<br/>
<h2 style="display: inline">通知详情</h2>
<a class="btn clear_second_button" href="#first"><i class="icon-remove"></i></a>
<dl class="dl-horizontal">
    <dt>标题</dt>
    <dd>{{ notice.title }}</dd>
    <dt>时间</dt>
    <dd>{{ notice.time|date:"Y-m-d" }}</dd>
    <dt>创建人</dt>
    <dd>
            {% ifequal enCalendar True %}
            <a class="get_others_calendar" url="/calendar/{{ notice.creator.id }}/"
               href="#third">{{ notice.creator }}</a>
        {% else %}
            {% ifequal calendar|staff_in:notice.creator True %}
                <a class="get_others_calendar" url="/calendar/{{ notice.creator.id }}/"
                   href="#third">{{ notice.creator }}</a>
            {% else %}
                {{ notice.creator }}
            {% endifequal %}
        {% endifequal %}

    </dd>
    <dt>内容</dt>
    <dd>{{ notice.content }}</dd>
</dl>

myapp/templates/notice/notice_list.html
{% extends 'app/layout.html' %}
{% load dictionary_extras %}
{% block first %}
{% include "messages.html" %}
{% include "dataTables.html" %}
{% include "frame.html" %}
<legend><h1>所有通知</h1></legend>
    <table class="table table-hover row-fluid table_show_detail" >
        <thead>
        <tr>
            <th class="span2"><input type="text"  value="标题" class="search_init"></th>
            <th class="span2"><input type="text"  value="时间" class="search_init"></th>
            <th class="span2"><input type="text"  value="创建人" class="search_init"></th>
            <th class="span4"><input type="text"  value="内容" class="search_init"></th>
            <th class="span2"></th>
        </tr>
        <tr>
            <th class="span2">标题</th>
            <th class="span2">时间</th>
            <th class="span2">创建人</th>
            <th class="span4">内容</th>
            <th class="span2 noFilter">操作</th>
        </tr>
        </thead>
        <tbody>
        {% for notice in notice_list %}
            <tr>
                <td><a class="detail_button" url="/notice/detail_notice/{{ notice.id }}/" href="#">{{ notice.title }}</a></td>
                <td>{{ notice.time|date:"Y-m-d" }}</td>
                <td>{{ notice.creator }}</td>
                <td>{{ notice.content|slice:"30"}}{% if notice.content|length > 30 %}...{% endif %}</td>
                <td>
                    {% if  staff.role.editMeeting or notice.creator.id == staff.id %}
                        <a
                                href="/notice/delete_notice/{{ notice.id }}/"
                                class="btn btn-primary "
                                onclick="if(confirm('删除后不可恢复，确定删除吗？')){return true;}return false;"
                                >删除
                        </a>
                    {% endif %}

                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
        <script>
     $(document).ready(function () {
        $('.nav li').removeClass('active');
        $('.get_notice_select').parent().addClass('active');

    });
    </script>{% endblock %}