myapp/app/urls.py
from django.conf.urls import patterns, url
from app import views
from task import views as t_view
#from  notice import  views as n_views

urlpatterns = patterns('',
                       # url(r'^$', views.index, name='index'),
                       # url(r'^test/$', t_view.created_task),
                       url(r'^login/$', views.user_login),
                       url(r'^logout/$', views.user_logout),
                       url(r'^change_password/$', views.change_password),
)

myapp/grappelli/urls.py
# coding: utf-8

# DJANGO IMPORTS
try: 
    from django.conf.urls import url, patterns
except ImportError: 
    # for Django version less then 1.4
    from django.conf.urls.defaults import url, patterns

from django.views.generic.base import TemplateView
from .views.related import RelatedLookup, M2MLookup, AutocompleteLookup
from .views.switch import switch_user


urlpatterns = patterns('',

    # FOREIGNKEY & GENERIC LOOKUP
    url(r'^lookup/related/$', RelatedLookup.as_view(), name="grp_related_lookup"),
    url(r'^lookup/m2m/$', M2MLookup.as_view(), name="grp_m2m_lookup"),
    url(r'^lookup/autocomplete/$', AutocompleteLookup.as_view(), name="grp_autocomplete_lookup"),

    # SWITCH USER
    url(r'^switch/user/(?P<object_id>\d+)/$', switch_user, name="grp_switch_user"),

    # GRAPPELLI DOM DOCUMENTATION
    url(r'^grp-doc/change-form/', TemplateView.as_view(template_name='grp_doc/change_form.html'), name="grp_doc_change_form"),
    url(r'^grp-doc/change-list/', TemplateView.as_view(template_name='grp_doc/change_list.html'), name="grp_doc_change_list"),
    url(r'^grp-doc/admin-index/', TemplateView.as_view(template_name='grp_doc/admin_index.html'), name="grp_doc_admin_index"),

    url(r'^grp-doc/tables/', TemplateView.as_view(template_name='grp_doc/tables.html'), name="grp_doc_tables"),

    url(r'^grp-doc/pagination/', TemplateView.as_view(template_name='grp_doc/pagination.html'), name="grp_doc_pagination"),
    url(r'^grp-doc/search-form/', TemplateView.as_view(template_name='grp_doc/search_form.html'), name="grp_doc_search_form"),
    url(r'^grp-doc/filter/', TemplateView.as_view(template_name='grp_doc/filter.html'), name="grp_doc_filter"),
    url(r'^grp-doc/date-hierarchy/', TemplateView.as_view(template_name='grp_doc/date_hierarchy.html'), name="grp_doc_date_hierarchy"),

    url(r'^grp-doc/fieldsets/', TemplateView.as_view(template_name='grp_doc/fieldsets.html'), name="grp_doc_fieldsets"),
    url(r'^grp-doc/errors/', TemplateView.as_view(template_name='grp_doc/errors.html'), name="grp_doc_errors"),
    url(r'^grp-doc/form-fields/', TemplateView.as_view(template_name='grp_doc/form_fields.html'), name="grp_doc_form_fields"),
    url(r'^grp-doc/submit-rows/', TemplateView.as_view(template_name='grp_doc/submit_rows.html'), name="grp_doc_submit_rows"),

    url(r'^grp-doc/modules/', TemplateView.as_view(template_name='grp_doc/modules.html'), name="grp_doc_modules"),
    url(r'^grp-doc/groups/', TemplateView.as_view(template_name='grp_doc/groups.html'), name="grp_doc_groups"),

    url(r'^grp-doc/navigation/', TemplateView.as_view(template_name='grp_doc/navigation.html'), name="grp_doc_navigation"),
    url(r'^grp-doc/context-navigation/', TemplateView.as_view(template_name='grp_doc/context_navigation.html'), name="grp_doc_context_navigation"),

    url(r'^grp-doc/basic-page-structure/', TemplateView.as_view(template_name='grp_doc/basic_page_structure.html'), name="grp_doc_basic_page_structure"),

    url(r'^grp-doc/tools/', TemplateView.as_view(template_name='grp_doc/tools.html'), name="grp_doc_tools"),
    url(r'^grp-doc/object-tools/', TemplateView.as_view(template_name='grp_doc/object_tools.html'), name="grp_doc_object_tools"),

    url(r'^grp-doc/mueller-grid-system-tests/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system_tests.html'), name="grp_doc_mueller_grid_system_tests"),
    url(r'^grp-doc/mueller-grid-system/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system.html'), name="grp_doc_mueller_grid_system"),
    url(r'^grp-doc/mueller-grid-system-layouts/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system_layouts.html'), name="grp_doc_mueller_grid_system_layouts"),

    url(r'^grp-doc', TemplateView.as_view(template_name='grp_doc/index.html'), name="grp_doc"),

)

myapp/myapp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from filebrowser.sites import site

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myapp.views.home', name='home'),
    # url(r'^myapp/', include('myapp.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:

    url(r'^$','app.views.index',name='Home'),
    url(r'^app/', include('app.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^calendar/', include('myCalendar.urls')),

    url(r'^staff/', include('staff.urls')),
    url(r'^notice/', include('notice.urls')),
    url(r'^meeting/', include('meeting.urls')),
    url(r'^task/', include('task.urls')),
    url(r'^bug/', include('bug.urls')),
    url(r'^filebrowser/', include(site.urls)),
)
urlpatterns += staticfiles_urlpatterns()

myapp/task/urls.py
__author__ = 'Maple'
from django.conf.urls import patterns, url
from task import views

urlpatterns = patterns('',
                       url(r'^show_task/$', views.show_task),
                       url(r'^all_task/$', views.all_task),
                       url(r'^(?P<my_id>\d+)/show_detail/$', views.show_detail, name="task"),
                       url(r'^task_detail/(.+)/$', views.show_detail),
                       url(r'^add_task/$', views.add_task),
                       url(r'^created_task/$', views.created_task),
                       url(r'^doing_task/$', views.doing_task),
                       url(r'^executed_task/$', views.executed_task),
                       url(r'^comments/p1(\w+)p2(.+)/$', views.comments),
                       url(r'^delete/(.+)/$', views.delete),
                       url(r'^deleteTree/(.+)/$', views.deleteTree),
                       url(r'^checked/(.+)/$', views.checked),
                       url(r'^affirm/(.+)/$', views.affirm),
                       url(r'^submit/(.+)/$', views.submit),
                       #url(r'^modify/p1(\w+)p2(.+)/$', views.modify),
                       url(r'^modify/(.+)/$', views.modify),
                       url(r'^psb_vsb/(.+)/$', views.psb_vsb),
                       url(r'^add_comment/p1(\w+)p2(.+)p3(.+)/$', views.add_comment),
                       url(r'^psb_vsb_add/p1(\w+)p2(.+)/$', views.psb_vsb_add),
                       url(r'^schedule/p1(\w+)p2(.+)/$', views.add_schedule),
                       url(r'^create_taskTemp/(.+)/$', views.create_tsktemp),
                       url(r'^taskTemplate/$', views.taskTemplate),
                       url(r'^addByTemp/(.+)/$', views.addByTemp),
                       url(r'^selectTemp/$', views.selectTemp),
                       url(r'^selTemp_addTsk/(.+)/$', views.selTemp_addTsk),
                       url(r'^delTemp/(.+)/$', views.delTemp),
                       url(r'^get_comments/(?P<task_id>\d+)/$', views.get_comments),
                       url(r'^get_feedbacks/(?P<task_id>\d+)/$', views.get_feedbacks),
)

myapp/app/models.py
#-*- coding: UTF-8 -*-
from django.db import models
from  django.contrib.auth.models import User
# Create your models here.
from mptt.models import MPTTModel, TreeForeignKey


class Role(models.Model):
    name = models.CharField(max_length=20)
    level = models.PositiveSmallIntegerField(default=5)  #the smaller the power
    editStaff = models.BooleanField(default=True)
    editTask = models.BooleanField(default=True)
    editCalendar = models.BooleanField(default=True)
    editMeeting = models.BooleanField(default=True)
    exportFile = models.BooleanField(default=True)

    def __unicode__(self):
        return self.name


class Staff(models.Model):
    user = models.OneToOneField(User, unique=True, related_name='staff')
    name = models.CharField(max_length=20)
    gender = models.BooleanField(default=True)  #True:man
    visible = models.BooleanField(default=True)
    role = models.ForeignKey(Role, related_name='staff')
    content = models.CharField(max_length=1024)
    visibleStaff = models.ManyToManyField("self", verbose_name='可见度', symmetrical=False, related_name='visibleCalendar',
                                          null=True)

    def __unicode__(self):
        return self.name


class Group(models.Model):
    name = models.CharField(max_length=20)
    member = models.ManyToManyField(Staff, related_name='group', blank=True, null=True)
    leader = models.ForeignKey(Staff, related_name='leader', blank=True, null=True)
    content = models.CharField(max_length=1024)

    def __unicode__(self):
        return self.name


class Task(MPTTModel):
    name = models.CharField(max_length=20, verbose_name='名称')
    creator = models.ForeignKey(Staff, related_name='created', verbose_name='创建者')
    create_date = models.DateTimeField()
    begin_date = models.DateTimeField(verbose_name='开始日期')
    end_date = models.DateTimeField(verbose_name='结束日期')
    state = models.IntegerField(verbose_name='状态')
    importance = models.IntegerField(verbose_name='等级')
    content = models.TextField(verbose_name='内容', max_length=1024)
    finish = models.TextField(max_length=1024, verbose_name='完成标志', blank=True, null=True)
    parent = TreeForeignKey('self', verbose_name='父任务', related_name='child', blank=True, null=True)
    principal = models.ForeignKey(Staff, verbose_name='负责人', related_name='directed')
    executor = models.ManyToManyField(Staff, verbose_name='执行人', related_name='task', null=True)
    group = models.ManyToManyField(Group, verbose_name='所属组', related_name='group', blank=True, null=True)
    viewing = models.ManyToManyField(Staff, verbose_name='可见性', related_name='viewing', null=True)
    inername = models.IntegerField(verbose_name='名称', blank=True, null=True)
    istemp = models.IntegerField(verbose_name='是否模板', default=0)

    class MPTTMeta:
        level_attr = 'mptt_level'
        order_insertion_by = ['-begin_date']

    def __unicode__(self):
        return self.name

    def clone(self):
        tsk = Task()
        tsk.name = self.name
        tsk.creator = self.creator
        tsk.create_date = self.create_date
        tsk.begin_date = self.begin_date
        tsk.end_date = self.end_date
        tsk.state = self.state
        tsk.importance = self.importance
        tsk.content = self.content
        tsk.finish = self.finish
        tsk.parent = self.parent
        tsk.principal = self.principal
        return tsk


class Comment(models.Model):
    author = models.ForeignKey(User)
    date = models.DateTimeField()
    content = models.TextField(max_length=1024, verbose_name='内容')
    task = models.ForeignKey(Task)
    type = models.IntegerField()

    def __unicode__(self):
        return self.author.username + ' comment:'


class Meeting(models.Model):
    name = models.CharField(max_length=30)
    time = models.DateTimeField()
    member = models.ManyToManyField(Staff, related_name='joined_meeting', blank=True, null=True)
    place = models.CharField(max_length=50)
    originator = models.ForeignKey(Staff)
    content = models.TextField()

    def __unicode__(self):
        return self.name


class Notice(models.Model):
    creator = models.ForeignKey(Staff, null=True)
    title = models.CharField(max_length=30)
    time = models.DateTimeField()
    content = models.TextField()

    def __unicode__(self):
        return self.title


class Calendar(models.Model):
    creator = models.ForeignKey(Staff)
    date = models.DateTimeField()
    summary = models.TextField(verbose_name='概括', null=True)
    content8 = models.TextField(null=True, default='')
    content9 = models.TextField(null=True, default='')
    content10 = models.TextField(null=True, default='')
    content11 = models.TextField(null=True, default='')
    content12 = models.TextField(null=True, default='')
    content13 = models.TextField(null=True, default='')
    content14 = models.TextField(null=True, default='')
    content15 = models.TextField(null=True, default='')
    content16 = models.TextField(null=True, default='')
    content17 = models.TextField(null=True, default='')
    content18 = models.TextField(null=True, default='')
    content19 = models.TextField(null=True, default='')
    content20 = models.TextField(null=True, default='')
    content21 = models.TextField(null=True, default='')
    content22 = models.TextField(null=True, default='')
    content23 = models.TextField(null=True, default='')
    #def __unicode__(self):
    #    return self.name


class Bug(models.Model):
    name = models.CharField(max_length=20, verbose_name='名称')
    creator = models.ForeignKey(Staff, related_name='b_creator', verbose_name='创建者')
    create_date = models.DateTimeField()
    begin_date = models.DateTimeField(verbose_name='开始日期')
    end_date = models.DateTimeField(verbose_name='结束日期')
    state = models.IntegerField(verbose_name='状态')
    importance = models.IntegerField(verbose_name='等级')
    content = models.TextField(verbose_name='内容', max_length=1024)
    finish = models.TextField(max_length=1024, verbose_name='完成标志', blank=True, null=True)
    task = models.ForeignKey(Task, verbose_name='所属任务', related_name='b_bug')
    principal = models.ForeignKey(Staff, verbose_name='负责人', related_name='b_principal')
    executor = models.ManyToManyField(Staff, verbose_name='执行人', related_name='b_executor', null=True)
    group = models.ManyToManyField(Group, verbose_name='所属组', related_name='b_group', blank=True, null=True)

    def __unicode__(self):
        return self.name


class BugComment(models.Model):
    author = models.ForeignKey(Staff)
    date = models.DateTimeField()
    content = models.TextField(max_length=1024, verbose_name='内容')
    bug = models.ForeignKey(Bug)
    type = models.IntegerField()

    def __unicode__(self):
        return self.author.name + " at " + self.date + " said: " + self.content + "\n"


class UnreadComment(models.Model):
    task = models.ForeignKey(Task, related_name='unread_comment')
    user = models.ForeignKey(Staff)
    counts = models.IntegerField(verbose_name='条数')

myapp/task/models.py
from django.db import models


# Create your models here.

myapp/templates/task/add_task.html
{% extends "app/layout.html" %}
{% load dictionary_extras %}
{% block first %}
{% include "messages.html" %}
{% include "staff_group.html" %}
{% include "frame.html" %}
{% load mptt_tags %}
<script type="text/javascript" language="JavaScript">
    $(document).ready(function () {
        $(document).on('input', '#finish', function () {
            var val = $('#finish').val();
            var len = val.length
            if (len > 1000)
                alert("完成标志的长度不能超过1000个字符,超过的部分在提交时会被截断!");
            $('#last_ch').text(1000 - len);
        });

{#        $('#temp').change(function () {#}
{#            var val = $('#temp').val()#}
{#            if (val != '-1') {#}
{#                var url = "/task/selTemp_addTsk/" + val + "/"#}
{#                $.get(url, function (data) {#}
{#                    $('#first').html(data);#}
{#                });#}
{#            }#}
{#            else {#}
{#                var url = "/task/add_task/"#}
{#                $.get(url, function (data) {#}
{#                    $('#first').html(data);#}
                    {#  $(".add_tsk").removeAttr("disabled");#}
{#                });#}
{#            }#}
{#        });#}

    });
</script>
<form method="post" action="/task/add_task/" class="form-horizontal">
    <fieldset>
        <legend><h1>创建项目</h1></legend>
        {% ifequal edit_task True %}
            <div class="control-group">
                <label class="control-label" for="id_name">选择模板创建项目:</label>

                <div class="controls">
                    <select id="temp" name="temp" onchange="self.location.href=options[selectedIndex].getAttribute('url')">
                        <option value="-1" url="/task/add_task/"></option>
                        {% for temp in temps %}
                            <option value="{{ temp.id }}" url="/task/selTemp_addTsk/{{ temp.id }}/"
                                    {% ifequal selTemp.id temp.id %} selected="true" {% endifequal %}>{{ temp }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        {% endifequal %}
        <div class="control-group">
            <label class="control-label" for="id_name">名称:<span style="color: red">&lowast;</span></label>

            <div class="controls">
                <input id="id_name" name="name" type="text" value="{{ t_name }}"/>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="id_begin_date">开始日期:<span style="color: red">&lowast;</span></label>

            <div class="controls">
                <input id="id_begin_date" name="begin_date" type="text" value="{{ t_begin_date |date:"Y-m-d" }}">(格式:
                YYYY-MM-DD)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="id_end_date">结束日期:<span style="color: red">&lowast;</span></label>

            <div class="controls">
                <input id="id_end_date" name="end_date" type="text" value="{{ t_end_data |date:"Y-m-d" }}">(格式:
                YYYY-MM-DD)
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">状态:</label>

            <div class="controls">
                <select name="state" id="imstate">
                    <option value="1" {% ifequal t_state '1' %}selected="true" {% endifequal %}>待确认</option>
                    <option value="2" {% ifequal t_state '2' %}selected="true" {% endifequal %}>进行中</option>
                    <option value="3" {% ifequal t_state '3' %}selected="true" {% endifequal %}>待审核</option>
                    <option value="4" {% ifequal t_state '4' %}selected="true" {% endifequal %}>已结束</option>
                </select>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">等级:</label>

            <div class="controls">
                <select name="importance" id="id_importance">
                    <option value="1" {% ifequal t_importance '1' %}selected="true" {% endifequal %}>一般</option>
                    <option value="2" {% ifequal t_importance '2' %}selected="true" {% endifequal %}>紧急</option>
                </select>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">内容:<span style="color: red">&lowast;</span></label>

            <div class="controls">
                <textarea name="content" id="content">{{ t_content }}</textarea>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">完成标志:</label>

            <div class="controls">
                <textarea name="finish" id="finish">{{ t_finish }}</textarea>(还可以输入<span id="last_ch">1000</span>个字符)
            </div>

        </div>

        <div class="control-group">
            <label class="control-label">父任务:</label>

            <div class="controls">
                <select name="parent" id="parent">
                    {# {% ifequal edit_task True %}#}
                    {#     <option {% ifequal t_parent None %}selected="true" {% endifequal %} value="None"></option>#}
                    {# {% endifequal %}#}
                    {# {% for p in parent %}#}
                    {#     <option value="{{ p.id }}"#}
                    {# {% ifequal t_parent p %}selected="true" {% endifequal %}>{{ p }}</option>#}
                    {# {% endfor %}#}
                    {% ifequal edit_task True %}
                        <option {% ifequal t_parent None %}selected="true" {% endifequal %} value="None"></option>
                    {% endifequal %}
                    {% for node,structure in parent|tree_info %}
                        <option value="{{ node.id }}" {% ifequal t_parent node %}selected="true" {% endifequal %}>
                            {% if not node.is_root_node %}
                                {% for i in node.get_level|n_range %}
                                    &nbsp;&nbsp;
                                {% endfor %}
                                {# {% for i in  1|n_range %}#}
                                {#     <strong>0</strong>#}
                                {# {% endfor %}#}
                            {% endif %}
                            {{ node }}
                        </option>
                    {% endfor %}
                </select>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">所属组:</label>

            <div class="controls">
                <select name="group" id="group" multiple="multiple">
                    {% for g in group %}
                        <option value="{{ g.id }}" {% for tg in t_group %}{% ifequal tg g %}selected="true"
                        {% endifequal %}{% endfor %}>
                            {{ g }}
                        </option>
                    {% endfor %}
                </select>按住Ctrl多选
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">负责人:<span style="color: red">&lowast;</span></label>

            <div class="controls">
                <select name="principal" id="principal" class="modalLink" href="#modal1_staff_radio"
                        onclick="setRadio_id('principal')">
                    <option value="{{ t_principal.id }}">{{ t_principal }}</option>
                </select>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">执行人:</label>

            <div class="controls">
                <select name="executor" multiple id="executor" class="modalLink" href="#modal1_staff_checkbox"
                        onclick="setCheckbox_id('executor')">
                    {% for e in t_executor %}
                        <option value="{{ e.id }}" selected>{{ e }}</option>
                    {% endfor %}
                </select>点击空白处进行选择
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">可见度:</label>

            <div class="controls">
                <select name="visible" multiple id="visible" class="modalLink" href="#modal1_staff_checkbox"
                        onclick="setCheckbox_id('visible')">
                    {% for v in t_visible %}
                        <option value="{{ v.id }}" selected>{{ v }}</option>
                    {% endfor %}
                </select>点击空白处进行选择
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn btn-primary toTop add_tsk">添加</button>
                <button type="reset" class="btn btn-primary toTop">清空</button>
            </div>
        </div>
    </fieldset>
</form>
<script>
     $(document).ready(function () {
        $('.nav li').removeClass('active');
        $('.add_task_select').parent().addClass('active');

    });
</script>{% endblock %}

myapp/templates/task/all_task.html
{% extends "app/layout.html" %}
{% load dictionary_extras %}
{% block first %}
    {% include "messages.html" %}
    {% include "dataTables.html" %}
    {% include "frame.html" %}

    <legend><h1>所有项目</h1></legend>
    <table class="table table-condensed table_show_detail">
        <thead>
        <tr>
            <th><input type="text" value="任务名称" class="search_init"></th>
            <th><input type="text" id="time_start1" value="开始时间始" class="search_init"></th>
            <th><input type="text" id="time_start2" value="开始时间止" class="search_init"></th>
            <th><input type="text" id="time_end1" value="结束时间始" class="search_init"></th>
            <th><input type="text" id="time_end2" value="结束时间止" class="search_init"></th>
            <th><input type="text" value="所属任务" class="search_init"></th>
            <th><input type="text" value="所属组" class="search_init"></th>
            <th><input type="text" value="创建人" class="search_init"></th>
            <th><input type="text" value="执行人" class="search_init"></th>
            <th><input type="text" style="display: none;"></th>
        </tr>
        <tr>
            <th>任务名称</th>
            <th>开始时间</th>
            <th>结束时间</th>
            <th>任务状态</th>
            <th>等级</th>
            <th>所属任务</th>
            <th>所属组</th>
            <th>创建人</th>
            <th>执行人</th>
            <th class="noFilter " colspan=1>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for task in tasks %}
            <tr>
                <td><a class="detail_button" url="{% url 'task' task.id %}" href="#second">{{ task.name }}</a></td>
                <td>{{ task.begin_date|date:"Y-m-d" }}</td>
                <td>{{ task.end_date|date:"Y-m-d" }}</td>
                <td>
                    {% ifequal task.state 1 %}
                        <span class="label label-important">待确认</span>
                    {% endifequal %}
                    {% ifequal task.state 2 %}
                        <span class="label label-info">进行中</span>
                    {% endifequal %}
                    {% ifequal task.state 3 %}<span class="label label-warning">待审核</span>{% endifequal %}
                    {% ifequal task.state 4 %}<span class="label label-success">已结束</span>{% endifequal %}
                </td>
                <td>
                    {% ifequal task.importance 1 %}一般{% endifequal %}
                    {% ifequal task.importance 2 %}紧急{% endifequal %}
                </td>
                <td>{{ task.parent }}</td>
                <td>
                    {% if task.group.all|length > 3 %}
                        {% for g in  task.group.all|slice:":3" %}
                            {{ g }};
                        {% endfor %}
                        ...
                    {% else %}
                        {% for g in  task.group.all %}
                            {{ g }};
                        {% endfor %}
                    {% endif %}
                </td>
                <td>
                    {{ task.creator }}
                </td>
                <td>
                    {% if task.executor.all|length > 3 %}
                        {% for e in  task.executor.all|slice:":3" %}
                            {{ e }};
                        {% endfor %}
                        ...
                    {% else %}
                        {% for e in  task.executor.all %}
                            {{ e }};
                        {% endfor %}
                    {% endif %}
                </td>
                <td colspan=1>
                    {% ifequal unread_comments|unrd_cmmt:task True %}
                        <a class="modalLink get_comments btn  btn-small btn-warning" task_id="{{ task.id }}"
                           href="#modal1_{{ task.id }}">评论<span style="display: none">new</span></a>
                    {% else %}
                        <a class="modalLink get_comments btn  btn-small btn-primary" task_id="{{ task.id }}"
                           href="#modal1_{{ task.id }}">评论</a>
                    {% endifequal %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="overlay"></div>
    {% for task in tasks %}
        <div id="modal1_{{ task.id }}" class="modal"
             style="display:none;margin: 0 auto;padding-left:15px;padding-top:10px;">
            <div id="comment_{{ task.id }}">
            </div>
            <form method="post"
                  action="/task/add_comment/p1{{ task.id }}p21p35/" class="form_comment" style="text-align: center">
                {{ nf.as_p }}
                <input type="submit" value="提交" class="btn btn-primary"/>&nbsp&nbsp&nbsp
                <button class="closeBtn btn btn-primary ">返回</button>
            </form>
        </div>
    {% endfor %}

    <script>
        $(document).ready(function () {
            $('.nav li').removeClass('active');
            $('.all_task_select').parent().addClass('active');
        });
    </script>
{% endblock %}

myapp/templates/task/get_comments.html
{% for c in comments %}
    {% ifequal c.type 1 %}
        {{ c.author }}&nbsp说：
        {{ c.content }}<br>
    {% endifequal %}
{% endfor %}

myapp/templates/task/get_feedbacks.html

         {% for c in comments %}
            {% ifequal c.type 2 %}
                    {{ c.author }}&nbsp说：
                    {{ c.content }}<br>
            {% endifequal %}
        {% endfor %}
