myapp/app/urls.py
from django.conf.urls import patterns, url
from app import views
from task import views as t_view
#from  notice import  views as n_views

urlpatterns = patterns('',
                       # url(r'^$', views.index, name='index'),
                       # url(r'^test/$', t_view.created_task),
                       url(r'^login/$', views.user_login),
                       url(r'^logout/$', views.user_logout),
                       url(r'^change_password/$', views.change_password),
)

myapp/grappelli/urls.py
# coding: utf-8

# DJANGO IMPORTS
try: 
    from django.conf.urls import url, patterns
except ImportError: 
    # for Django version less then 1.4
    from django.conf.urls.defaults import url, patterns

from django.views.generic.base import TemplateView
from .views.related import RelatedLookup, M2MLookup, AutocompleteLookup
from .views.switch import switch_user


urlpatterns = patterns('',

    # FOREIGNKEY & GENERIC LOOKUP
    url(r'^lookup/related/$', RelatedLookup.as_view(), name="grp_related_lookup"),
    url(r'^lookup/m2m/$', M2MLookup.as_view(), name="grp_m2m_lookup"),
    url(r'^lookup/autocomplete/$', AutocompleteLookup.as_view(), name="grp_autocomplete_lookup"),

    # SWITCH USER
    url(r'^switch/user/(?P<object_id>\d+)/$', switch_user, name="grp_switch_user"),

    # GRAPPELLI DOM DOCUMENTATION
    url(r'^grp-doc/change-form/', TemplateView.as_view(template_name='grp_doc/change_form.html'), name="grp_doc_change_form"),
    url(r'^grp-doc/change-list/', TemplateView.as_view(template_name='grp_doc/change_list.html'), name="grp_doc_change_list"),
    url(r'^grp-doc/admin-index/', TemplateView.as_view(template_name='grp_doc/admin_index.html'), name="grp_doc_admin_index"),

    url(r'^grp-doc/tables/', TemplateView.as_view(template_name='grp_doc/tables.html'), name="grp_doc_tables"),

    url(r'^grp-doc/pagination/', TemplateView.as_view(template_name='grp_doc/pagination.html'), name="grp_doc_pagination"),
    url(r'^grp-doc/search-form/', TemplateView.as_view(template_name='grp_doc/search_form.html'), name="grp_doc_search_form"),
    url(r'^grp-doc/filter/', TemplateView.as_view(template_name='grp_doc/filter.html'), name="grp_doc_filter"),
    url(r'^grp-doc/date-hierarchy/', TemplateView.as_view(template_name='grp_doc/date_hierarchy.html'), name="grp_doc_date_hierarchy"),

    url(r'^grp-doc/fieldsets/', TemplateView.as_view(template_name='grp_doc/fieldsets.html'), name="grp_doc_fieldsets"),
    url(r'^grp-doc/errors/', TemplateView.as_view(template_name='grp_doc/errors.html'), name="grp_doc_errors"),
    url(r'^grp-doc/form-fields/', TemplateView.as_view(template_name='grp_doc/form_fields.html'), name="grp_doc_form_fields"),
    url(r'^grp-doc/submit-rows/', TemplateView.as_view(template_name='grp_doc/submit_rows.html'), name="grp_doc_submit_rows"),

    url(r'^grp-doc/modules/', TemplateView.as_view(template_name='grp_doc/modules.html'), name="grp_doc_modules"),
    url(r'^grp-doc/groups/', TemplateView.as_view(template_name='grp_doc/groups.html'), name="grp_doc_groups"),

    url(r'^grp-doc/navigation/', TemplateView.as_view(template_name='grp_doc/navigation.html'), name="grp_doc_navigation"),
    url(r'^grp-doc/context-navigation/', TemplateView.as_view(template_name='grp_doc/context_navigation.html'), name="grp_doc_context_navigation"),

    url(r'^grp-doc/basic-page-structure/', TemplateView.as_view(template_name='grp_doc/basic_page_structure.html'), name="grp_doc_basic_page_structure"),

    url(r'^grp-doc/tools/', TemplateView.as_view(template_name='grp_doc/tools.html'), name="grp_doc_tools"),
    url(r'^grp-doc/object-tools/', TemplateView.as_view(template_name='grp_doc/object_tools.html'), name="grp_doc_object_tools"),

    url(r'^grp-doc/mueller-grid-system-tests/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system_tests.html'), name="grp_doc_mueller_grid_system_tests"),
    url(r'^grp-doc/mueller-grid-system/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system.html'), name="grp_doc_mueller_grid_system"),
    url(r'^grp-doc/mueller-grid-system-layouts/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system_layouts.html'), name="grp_doc_mueller_grid_system_layouts"),

    url(r'^grp-doc', TemplateView.as_view(template_name='grp_doc/index.html'), name="grp_doc"),

)

myapp/meeting/urls.py
__author__ = 'whiteworld'
from  django.conf.urls import patterns, url
from  meeting import views

urlpatterns = patterns('',
                       url(r'^create_meeting/$', views.create_meeting),
                       url(r'^get_meeting/$', views.get_meeting),
                       url(r'^detail_meeting/(?P<id>\d+)/$', views.detail_meeting),
                       url(r'^delete_meeting/(?P<id>\d+)/$', views.delete_meeting),

)

myapp/myapp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from filebrowser.sites import site

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myapp.views.home', name='home'),
    # url(r'^myapp/', include('myapp.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:

    url(r'^$','app.views.index',name='Home'),
    url(r'^app/', include('app.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^calendar/', include('myCalendar.urls')),

    url(r'^staff/', include('staff.urls')),
    url(r'^notice/', include('notice.urls')),
    url(r'^meeting/', include('meeting.urls')),
    url(r'^task/', include('task.urls')),
    url(r'^bug/', include('bug.urls')),
    url(r'^filebrowser/', include(site.urls)),
)
urlpatterns += staticfiles_urlpatterns()

myapp/app/models.py
#-*- coding: UTF-8 -*-
from django.db import models
from  django.contrib.auth.models import User
# Create your models here.
from mptt.models import MPTTModel, TreeForeignKey


class Role(models.Model):
    name = models.CharField(max_length=20)
    level = models.PositiveSmallIntegerField(default=5)  #the smaller the power
    editStaff = models.BooleanField(default=True)
    editTask = models.BooleanField(default=True)
    editCalendar = models.BooleanField(default=True)
    editMeeting = models.BooleanField(default=True)
    exportFile = models.BooleanField(default=True)

    def __unicode__(self):
        return self.name


class Staff(models.Model):
    user = models.OneToOneField(User, unique=True, related_name='staff')
    name = models.CharField(max_length=20)
    gender = models.BooleanField(default=True)  #True:man
    visible = models.BooleanField(default=True)
    role = models.ForeignKey(Role, related_name='staff')
    content = models.CharField(max_length=1024)
    visibleStaff = models.ManyToManyField("self", verbose_name='可见度', symmetrical=False, related_name='visibleCalendar',
                                          null=True)

    def __unicode__(self):
        return self.name


class Group(models.Model):
    name = models.CharField(max_length=20)
    member = models.ManyToManyField(Staff, related_name='group', blank=True, null=True)
    leader = models.ForeignKey(Staff, related_name='leader', blank=True, null=True)
    content = models.CharField(max_length=1024)

    def __unicode__(self):
        return self.name


class Task(MPTTModel):
    name = models.CharField(max_length=20, verbose_name='名称')
    creator = models.ForeignKey(Staff, related_name='created', verbose_name='创建者')
    create_date = models.DateTimeField()
    begin_date = models.DateTimeField(verbose_name='开始日期')
    end_date = models.DateTimeField(verbose_name='结束日期')
    state = models.IntegerField(verbose_name='状态')
    importance = models.IntegerField(verbose_name='等级')
    content = models.TextField(verbose_name='内容', max_length=1024)
    finish = models.TextField(max_length=1024, verbose_name='完成标志', blank=True, null=True)
    parent = TreeForeignKey('self', verbose_name='父任务', related_name='child', blank=True, null=True)
    principal = models.ForeignKey(Staff, verbose_name='负责人', related_name='directed')
    executor = models.ManyToManyField(Staff, verbose_name='执行人', related_name='task', null=True)
    group = models.ManyToManyField(Group, verbose_name='所属组', related_name='group', blank=True, null=True)
    viewing = models.ManyToManyField(Staff, verbose_name='可见性', related_name='viewing', null=True)
    inername = models.IntegerField(verbose_name='名称', blank=True, null=True)
    istemp = models.IntegerField(verbose_name='是否模板', default=0)

    class MPTTMeta:
        level_attr = 'mptt_level'
        order_insertion_by = ['-begin_date']

    def __unicode__(self):
        return self.name

    def clone(self):
        tsk = Task()
        tsk.name = self.name
        tsk.creator = self.creator
        tsk.create_date = self.create_date
        tsk.begin_date = self.begin_date
        tsk.end_date = self.end_date
        tsk.state = self.state
        tsk.importance = self.importance
        tsk.content = self.content
        tsk.finish = self.finish
        tsk.parent = self.parent
        tsk.principal = self.principal
        return tsk


class Comment(models.Model):
    author = models.ForeignKey(User)
    date = models.DateTimeField()
    content = models.TextField(max_length=1024, verbose_name='内容')
    task = models.ForeignKey(Task)
    type = models.IntegerField()

    def __unicode__(self):
        return self.author.username + ' comment:'


class Meeting(models.Model):
    name = models.CharField(max_length=30)
    time = models.DateTimeField()
    member = models.ManyToManyField(Staff, related_name='joined_meeting', blank=True, null=True)
    place = models.CharField(max_length=50)
    originator = models.ForeignKey(Staff)
    content = models.TextField()

    def __unicode__(self):
        return self.name


class Notice(models.Model):
    creator = models.ForeignKey(Staff, null=True)
    title = models.CharField(max_length=30)
    time = models.DateTimeField()
    content = models.TextField()

    def __unicode__(self):
        return self.title


class Calendar(models.Model):
    creator = models.ForeignKey(Staff)
    date = models.DateTimeField()
    summary = models.TextField(verbose_name='概括', null=True)
    content8 = models.TextField(null=True, default='')
    content9 = models.TextField(null=True, default='')
    content10 = models.TextField(null=True, default='')
    content11 = models.TextField(null=True, default='')
    content12 = models.TextField(null=True, default='')
    content13 = models.TextField(null=True, default='')
    content14 = models.TextField(null=True, default='')
    content15 = models.TextField(null=True, default='')
    content16 = models.TextField(null=True, default='')
    content17 = models.TextField(null=True, default='')
    content18 = models.TextField(null=True, default='')
    content19 = models.TextField(null=True, default='')
    content20 = models.TextField(null=True, default='')
    content21 = models.TextField(null=True, default='')
    content22 = models.TextField(null=True, default='')
    content23 = models.TextField(null=True, default='')
    #def __unicode__(self):
    #    return self.name


class Bug(models.Model):
    name = models.CharField(max_length=20, verbose_name='名称')
    creator = models.ForeignKey(Staff, related_name='b_creator', verbose_name='创建者')
    create_date = models.DateTimeField()
    begin_date = models.DateTimeField(verbose_name='开始日期')
    end_date = models.DateTimeField(verbose_name='结束日期')
    state = models.IntegerField(verbose_name='状态')
    importance = models.IntegerField(verbose_name='等级')
    content = models.TextField(verbose_name='内容', max_length=1024)
    finish = models.TextField(max_length=1024, verbose_name='完成标志', blank=True, null=True)
    task = models.ForeignKey(Task, verbose_name='所属任务', related_name='b_bug')
    principal = models.ForeignKey(Staff, verbose_name='负责人', related_name='b_principal')
    executor = models.ManyToManyField(Staff, verbose_name='执行人', related_name='b_executor', null=True)
    group = models.ManyToManyField(Group, verbose_name='所属组', related_name='b_group', blank=True, null=True)

    def __unicode__(self):
        return self.name


class BugComment(models.Model):
    author = models.ForeignKey(Staff)
    date = models.DateTimeField()
    content = models.TextField(max_length=1024, verbose_name='内容')
    bug = models.ForeignKey(Bug)
    type = models.IntegerField()

    def __unicode__(self):
        return self.author.name + " at " + self.date + " said: " + self.content + "\n"


class UnreadComment(models.Model):
    task = models.ForeignKey(Task, related_name='unread_comment')
    user = models.ForeignKey(Staff)
    counts = models.IntegerField(verbose_name='条数')

myapp/meeting/models.py
from django.db import models

# Create your models here.

myapp/meeting/views.py
#-*- coding: UTF-8 -*-
# Create your views here.
from app.models import Meeting, Staff
from django.template import RequestContext
from django.shortcuts import render_to_response, render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django import forms
from django.contrib.auth.models import User
import socket
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from app.views import permission_required_with,valid_time, cache_on_auth
import  datetime
from app.models import Group
from django.core.cache import cache
from django.views.decorators.cache import cache_page

class MeetingForm(forms.ModelForm):
    name = forms.CharField()
    time = forms.DateTimeField()
    place = forms.CharField()
    content = forms.Textarea()
    class Meta:
        model = Meeting
        exclude = ('originator',)


@login_required(login_url="/app/login/")
#@permission_required_with('meeting')
# @cache_on_auth(60 * 15)
def get_meeting(request):
    context = RequestContext(request)
    meetings = Meeting.objects.all()
    return render_to_response('meeting/meeting_list.html', {'meeting_list': meetings, 'url': request.path,'staff':request.user.staff}, context)

@login_required(login_url="/app/login/")
def delete_meeting(request, id):
    context = RequestContext(request)
    Meeting.objects.get(id=id).delete()
    cache.clear()
    messages.success(request, '删除成功！')
    meetings = Meeting.objects.all()
    return render_to_response('meeting/meeting_list.html', {'meeting_list': meetings, 'url': request.path,'staff':request.user.staff}, context)

@login_required(login_url="/app/login/")
#@permission_required_with('meeting')
def detail_meeting(request, id):
    context = RequestContext(request)
    meeting = Meeting.objects.get(id=id)
    enablecalendar = request.user.staff.role.editCalendar
    calendar = request.user.staff.visibleCalendar.all()
    return render_to_response('meeting/detail_meeting.html', {'calendar': calendar, 'enCalendar': enablecalendar,'staff': request.user.staff,'meeting': meeting}, context)


@login_required(login_url="/app/login/")
#@permission_required_with('meeting')
def create_meeting(request):
    context = RequestContext(request)
    group = Group.objects.all()
    ngroup = Staff.objects.filter(group=None)
    if request.method == 'POST':
        name = request.POST.get('name')
        time = request.POST.get('time')
        place = request.POST.get('place')
        content = request.POST.get('content')
        my_dict = dict(request.POST.iterlists())
        member = []
        if my_dict.get('member'):
            for m in my_dict['member']:
                member.append(Staff.objects.get(id=m))
        if name == '':
            messages.error(request, "请填写标题！")
        elif time == '':
            messages.error(request, "请选择时间！")
        elif place == '':
            messages.error(request, "请填写地点！")
        elif content == '':
            messages.error(request, "请填写内容！")
        elif len(name) > 30:
            messages.error(request,"名称太长（应不大于30个字）！")
        elif not valid_time(time):
            messages.error(request, "时间格式不正确！")
        elif len(place) > 50:
            messages.error(request,'地点太长（应不大于50字）！')
        else:
            meeting = Meeting()
            meeting.name = name
            meeting.time = time
            meeting.place = place
            meeting.originator = request.user.staff
            meeting.content = content
            meeting.save()
            for m in member:
                meeting.member.add(m)

            messages.success(request,'创建会议成功！')
            return  redirect("/meeting/get_meeting/")
            cache.clear()
        return render_to_response('meeting/create_meeting.html',
                                      {'staff': request.user.staff,'name': name, 'time': time, 'place': place,
                                       'content': content,'group':group,'ngroup':ngroup,'member':member},
                                      context)
    return render_to_response('meeting/create_meeting.html',{'staff': request.user.staff,'group':group,'ngroup':ngroup,}, context)

myapp/templates/meeting/create_meeting.html
{% extends 'app/layout.html' %}
{% block first %}
{% include "messages.html" %}
{% include "frame.html" %}
{% include "staff_group.html" %}
<legend><h1>发布会议</h1></legend>
<form method="post" action="/meeting/create_meeting/" class="form-horizontal ">
    <div class="control-group">
        <label class="control-label" for="id_name">会议名称:<span style="color: red">&lowast;</span></label>
        <div class="controls">
            <input id="id_name" name="name" type="text" value="{{ name }}"/>
        </div>
    </div>


    <div class="control-group">
        <label  class="control-label" for="id_time">会议时间:<span style="color: red">&lowast;</span></label>
        <div class="controls">
            <input id="id_time" name="time" type="text" value="{{ time }}">(格式: YYYY-MM-DD)
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="id_place">会议地点:<span style="color: red">&lowast;</span></label>
        <div class="controls">
            <input id="id_place" name="place" type="text" value="{{ place }}"/></p>

        </div>
    </div>



    <div class="control-group">
        <label class="control-label">参加人员:<span style="color: red">&lowast;</span></label>

        <div class="controls">
            <select name="member" multiple id="id_member" class="modalLink" href="#modal1_staff_checkbox"
                    onclick="setCheckbox_id('id_member')">
            </select>点击空白处进行选择
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="id_content">会议简介:<span style="color: red">&lowast;</span></label>

        <div class="controls">
            <textarea cols="40" id="id_content" name="content" rows="10">{{ content }}</textarea>

        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn btn-primary toTop">发布</button>
            <button class="btn btn-primary back_button toTop" iid="create_meeting">清空</button>

        </div>
    </div>
</form>
        <script>
     $(document).ready(function () {
        $('.nav li').removeClass('active');
        $('.create_meeting_select').parent().addClass('active');

    });
    </script>
{% endblock %}

myapp/templates/meeting/detail_meeting.html
{% load dictionary_extras %}
<br/>
<br/>
<br/>
<h2 style="display: inline">会议详情</h2>
<a class="btn clear_second_button" href="#first"><i class="icon-remove"></i></a>
<dl class="dl-horizontal">
    <dt>名称</dt>
    <dd>{{ meeting.name }}</dd>
    <dt>时间</dt>
    <dd>{{ meeting.time|date:"Y-m-d" }}</dd>
    <dt>地点</dt>
    <dd>{{ meeting.place }}</dd>
    <dt>发起人</dt>
    <dd>
                {% ifequal enCalendar True %}
            <a class="get_others_calendar" url="/calendar/{{ meeting.originator.id }}/"
               href="#third">{{ meeting.originator }}</a>
        {% else %}
            {% ifequal calendar|staff_in:meeting.originator True %}
                <a class="get_others_calendar" url="/calendar/{{ meeting.originator.id }}/"
                   href="#third">{{ meeting.originator }}</a>
            {% else %}
                {{ meeting.originator }}
            {% endifequal %}
        {% endifequal %}
    </dd>
    <dt>参加人</dt>
    <dd>{% for m in meeting.member.all %}
{% ifequal enCalendar True %}
                <a class="get_others_calendar" url="/calendar/{{ m.id }}/" href="#third">{{ m }} </a>
            {% else %}
                {% ifequal calendar|staff_in:m True %}
                    <a class="get_others_calendar" url="/calendar/{{ m.id }}/" href="#third">{{ m }} </a>
                {% else %}
                    {{ m }}
                {% endifequal %}
            {% endifequal %}
    {% endfor %}</dd>
    <dt>内容</dt>
    <dd>{{ meeting.content }}</dd>
</dl>

myapp/templates/meeting/meeting_list.html
{% extends 'app/layout.html' %}
{% load dictionary_extras %}
{% block first %}
{% include "messages.html" %}
{% include "dataTables.html" %}
{% include "frame.html" %}
<legend><h1>所有会议</h1></legend>
    <table class="table table-hover row-fluid table_show_detail" >
        <thead>
        <tr>
            <th class="span1"><input type="text"  value="名称" class="search_init"></th>
            <th class="span1"><input type="text"  value="时间" class="search_init"></th>
            <th class="span1"><input type="text"  value="地点" class="search_init"></th>
            <th class="span1"><input type="text"  value="发起人" class="search_init"></th>
            <th class="span1"><input type="text"  value="参加人" class="search_init"></th>
            <th class="span1"><input type="text"  value="内容" class="search_init"></th>
            <th class="span1"></th>
        </tr>
        <tr>
            <th class="span1">名称</th>
            <th class="span1">时间</th>
            <th class="span1">地点</th>
            <th class="span1">发起人</th>
            <th class="span1">参加人</th>
            <th class="span1">内容</th>
            <th class="span1 noFilter">操作</th>
        </tr>
        </thead>
        <tbody>
        {% for meeting in meeting_list %}
            <tr>
                <td><a class="detail_button" href="#second" url="/meeting/detail_meeting/{{ meeting.id }}/">{{ meeting.name }}</a></td>
                <td>{{ meeting.time|date:"Y-m-d" }}</td>
                <td>{{ meeting.place }}</td>
                <td>{{ meeting.originator }}</td>
                <td>
                    {% if meeting.member.all|length > 3 %}
                        {% for m in meeting.member.all|slice:":3" %}
                        {{m}};
                        {% endfor %}
                        ...
                    {% else %}
                        {% for m in meeting.member.all%}
                        {{m}};
                        {% endfor %}
                    {% endif %}
                </td>
                <td>{{ meeting.content| slice:"30" }}{% if meeting.content|length > 30 %}...{% endif %}</td>
                <td>
                    {% if staff.role.editMeeting or meeting.originator.id == staff.id %}

                        <a
                                href="/meeting/delete_meeting/{{ meeting.id }}/"
                                class="btn btn-primary "
                                onclick="if(confirm('删除后不可恢复，确定删除吗？')){return true;}return false;"
                                >删除
                        </a>
                    {% endif %}

                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
        <script>
     $(document).ready(function () {
        $('.nav li').removeClass('active');
        $('.get_meeting_select').parent().addClass('active');

    });
    </script>
{% endblock %}
{#{% include "pagination.html" with some_list=meeting_list url=url %}#}